### ISSUE TITLE
Editing "reset" button in German

### ISSUE THREAD

**Issue by CIGCAdmin** [davide-casiraghi/ci-global-calendar#108]
**Describe the bug**
The "Reset" button on the main page is wringly spelled in the German translation.

It should read "zurücksETZEN".
There is an extra T letter in the current spelling: zurücksETZ**_T_**EN 
Neither Ecki nor myself (Steff) has the editing rights for the interface content.

**Expected behavior**
Changing it to the correct orthography

**Screenshots**
See button in the bottom right hand corner
![Capture du 2019-04-26 15:48:48](https://user-images.githubusercontent.com/48979117/56812307-e623ab80-683a-11e9-893f-e6a37949831d.png)

**Comment by davide-casiraghi** [comment]
fixed

**Comment by CIGCAdmin** [comment]
Great thanks!!
