### ISSUE TITLE
Structure datas according to Google event search

### ISSUE THREAD

**Issue by davide-casiraghi** [davide-casiraghi/ci-global-calendar#141]
**We have received this email from Google**

Search Console has detected that your site contains event information that would benefit from enhanced Google Search results. Google Search supports an Event rich result that provides a richer user experience for events in search results, including event date, time, description and ticketing information.

Enabling Event rich results on your site is free, and requires only the proper structured data on your website. Early adopters who have implemented Event rich results have boosted site traffic significantly ([read a case study](https://www.google.com/appserve/mkt/p/AFnwnKXljkTMRAq6-FBr8ELnsaAdj8UySl1Ky_36nwCJ0rFVuZpk1vlnQpA-ZFQEuGRcddQgsyMEVVHSPZ3bGb8C40QYn2pFBvJyYGqfuehHzGaOTmGqx1G08MUFfLPwNJg-ltFmt5hD1gfit7MkZupsOGNj4WrxSCo6JijOvGP9769eLkvGmrSQeSo_B3P6Z3xQUkgLmmh09kVFF8oEwRkTaBMMoVQvxhosTXqZBtVkEZBHf4WVrcWrDX1B5NciPvv1b_OwLuwgL0LIFXtIYCSqrebmQ0NeKXadHKWcyCFeYQ)).

This events feature experience will be coming to your market soon!

To make your site eligible for Event rich results, follow the linked instructions.

**Solution**
Format the data's according to this guidelines.
[Google events guidelines ](https://developers.google.com/search/docs/data-types/event?utm_source=wnc_20078181&utm_medium=gamma&utm_campaign=wnc_20078181&utm_content=msg_110177662&hl=en-GB)

**Comment by davide-casiraghi** [comment]
Hey @mico , I'm considering to modify the api according to this Google guidelines.
I think it will bring many benefits.

Are u interested to contribute ?

**Comment by mico** [comment]
What I can do?

**Comment by davide-casiraghi** [comment]
I did not have time yet to read all the Google guidelines.
So, to proceed step by step we need to:

1.  Read the guidelines to understand how to modify the event api according to them.
2. Write here what we need to modify
3. Modify the event APIs

So if you feel for you can start with the first step. Or if you prefer just coding give me some days and I will read them.

**Comment by mico** [comment]
@davide-casiraghi I'm not interested in development for Laravel, I hate php :-)
But I'm interested to develop mobile client. So I just tries to improve api to be able to use it in mobile client.
I want to contribute to Laravel part as less as possible.

**Comment by davide-casiraghi** [comment]
Ok, :)
So just follow this post because the API will change when I will tune them
to the Google standard.

It's not priority at the moment but soon or before I will do it.

Thanks
Davide

**Comment by davide-casiraghi** [comment]
Eventbrite use Google Structured data. 
To see an example pick one event from [https://www.eventbrite.ca](https://www.eventbrite.ca) and check in the source code for:  

> <script type="application/ld+json">

**Comment by davide-casiraghi** [comment]
Example:   

```
<script type="application/ld+json">
	{
		"startDate":"2019-09-01T13:00:00+02:00",
		"endDate":"2019-09-01T18:00:00+02:00",
		"name":"Explicit Look \u0026 Learn",
		"url":"https://www.eventbrite.ca/e/explicit-look-learn-tickets-65108303689",
		"image":"https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F66547939%2F240185550573%2F1%2Foriginal.20190725-165317?w=1000\u0026auto=compress\u0026rect=0%2C0%2C2160%2C1080\u0026s=629baf43602419631588483d2b17cd45",
		"eventStatus":"EventScheduled",
		"offers":[
			{
				"availabilityEnds":"2019-09-01T10:00:00Z",
				"priceCurrency":"EUR",
				"url":"https://www.eventbrite.ca/e/explicit-look-learn-tickets-65108303689",
				"lowPrice":33.22,
				"highPrice":33.22,
				"@type":"AggregateOffer",
				"availabilityStarts":"2019-07-10T06:15:00Z",
				"validFrom":"2019-07-10T06:15:00Z",
				"availability":"InStock"
			},
			{
				"availabilityEnds":"2019-09-01T10:00:00Z",
				"name":"General Admission",
				"priceCurrency":"EUR",
				"url":"https://www.eventbrite.ca/e/explicit-look-learn-tickets-65108303689",
				"price":33.22,"@type":"Offer","availabilityStarts":"2019-07-10T06:15:00Z",
				"validFrom":"2019-07-10T06:15:00Z","availability":"InStock"
			}
		],
		"location":{
			"address":
				{
					"addressCountry":"SI",
					"addressLocality":"Ljubljana",
					"addressRegion":"Ljubljana",
					"streetAddress":"16 \u017delezna cesta, 1000 Ljubljana",
					"postalCode":"1000","@type":"PostalAddress"
				},
			"@type":"Place",
			"name":"\u017delezna Studio"
		},
			"@context":"http://schema.org",
			"organizer":{
				"url":"https://www.eventbrite.ca/o/idriz-dragonjic-zig-25383244579",
				"@type":"Organization",
				"name":"Idriz Dragonjic-\u201cZig\u201d"
			},
			"@type":"EducationEvent",
			"description":"Hey Slovenia! Come and experience latest trends in Men\u2019s hair industry.\nIn this class you will discover latest techniques that you can apply to your existing knowledge and improve your overall skill set. Whether you are a beginner or advanced barber this class is for you.\u00a0\n\nDont miss your chance! Limited amount of seats!\n\n\nHej Slovenija!Vas zanimajo najnovej\u0161i trendi mo\u0161kega stri\u017eenja?\nNa delavnici vas bom seznanil s sve\u017eimi tehnikami stri\u017eenja, ki so primerne za vse stopnje predznanja. Prijavite se lahko tako vsi - za\u010detniki in izku\u0161eni.\nNe izpustite res dobre prilo\u017enosti in se prijavite takoj saj je \u0161tevilo prijav omejeno!"
	}
</script>
```

**Comment by davide-casiraghi** [comment]
To test the google structured datas use this tool:  
[https://search.google.com/structured-data/testing-tool/u/0/?hl=en-GB](https://search.google.com/structured-data/testing-tool/u/0/?hl=en-GB)

**Comment by davide-casiraghi** [comment]
Done,  
now in the event show view the google structured data are shown inside this tag.
```
<script type="application/ld+json">
...
</script>
```
