### ISSUE TITLE
Geographical search _ by radius / distance

### ISSUE THREAD

**Issue by CIGCAdmin** [davide-casiraghi/ci-global-calendar#182]
**Is your feature request related to a problem? Please describe.**
For events that happen in an area in the middle of 3 main cities (as an example) and although it is possible to search by province / region, it is still difficult for some events to show up and to be found.

**Describe the solution you'd like**
The possibility to search by radius / distance from a given point (where someone lives / the nearby main city / etc.) would help people to locate smaller events or those in rural areas, more easily, especially if we consider big states with a lot of events (say: small rural events in a state like California where a lot happens)

**Describe alternatives you've considered**
For now, the possibility to search by state / region is already helpful as opposed to country-wide.

**Additional context**
On top of this, the possibility to see the result of that search on a map would be extra useful too!
Maybe using an opensource map like OpenStreetMap? Or Mapy.cz ?

**Comment by davide-casiraghi** [comment]
We can save the venue's GPS coordinates 
each time a venue get saved using this free API.

**Comment by davide-casiraghi** [comment]
Now GPS position of the venues is saved in the DB every time a venue get saved

**Comment by CIGCAdmin** [comment]
This sounds great, thanks Davide!

So if I understand properly, now all of the venues are localised with GPS
coordinates, which sounds like a great first step!
Can I ask though, if and how that makes a difference (for now) with the
search function?
People can not select a location and a radius for now, so it does not
enable to search by distance yet, right?

It is, however, a needed step in order to move towards a distance search! :)

Stephanie
For the CI Global Calendar Team

**Comment by davide-casiraghi** [comment]
It's just a first step to develop new search functionalities.
At the moment there is not yet any impact or difference in the search functionality.

**Comment by CIGCAdmin** [comment]
Well, a first step is always a step in the right direction. That's great! ;)

Stephanie
For the CI Global Calendar Team

**Comment by stawastawa** [comment]
excellent!

**Comment by davide-casiraghi** [comment]
We can use this service to generate the map to avoid using Google.
[https://github.com/Leaflet/Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster)
[https://leafletjs.com/](https://leafletjs.com/)

**Comment by davide-casiraghi** [comment]
Here are some options to geolocate Chinese addresses
https://lbs.amap.com/api/webservice/summary

https://www.programmableweb.com/api/amap/sdks
https://www.programmableweb.com/sdk/amap-php-sdk-sixteener
https://www.programmableweb.com/sdk/amap-php-sdk-g98051815
https://www.programmableweb.com/sdk/amap-php-sdk-jian-li
https://www.programmableweb.com/sdk/amap-php-sdk-axios

**Comment by davide-casiraghi** [comment]
Amap is probably the best option:

The address of the Geocode api looks like this:
https://restapi.amap.com/v3/geocode/geo?key=您的key&address=方恒国际中心A座&city=北京

**Comment by davide-casiraghi** [comment]
The first version of the map is available here:
https://ciglobalcalendar.net/geomap

**Comment by davide-casiraghi** [comment]
Further development is to add multiple events in one venue.
At the moment if there are two different active events in the same venue the markers are overlapped.

**Comment by CIGCAdmin** [comment]
Thanks Davide, that's a great evolution !!

Have you shared the good news with Ecki as well ? :)


Le mar. 17 mars 2020 à 17:38, Davide Casiraghi <notifications@github.com> a
écrit :
