### ISSUE TITLE
Bug in the teacher view

### ISSUE THREAD

**Issue by davide-casiraghi** [davide-casiraghi/ci-global-calendar#195]
**Describe the bug**
Davide Giacobbe reported a bug in the Teacher detail page.

Hello, a small bug: In the teachers' page, the below listed events related to the teacher, don't display the venue name and city (just a comma is displayed). e.g.: [https://ciglobalcalendar.net/teacher/michele-marchesani-81472](https://ciglobalcalendar.net/teacher/michele-marchesani-81472)

**To Reproduce**
1. Go to the page of a teacher that has some active events
3. Scroll down to the list of the events
4. See the venue details that are missing

**Comment by dagalumin** [comment]
As a reference, I tried a couple other teachers but the bug doesn't reproduce; you can see it just with the provided link regarding Michele Marchesani and the event I just inserted. Maybe something happening just with freshly inserted events?
