### ISSUE TITLE
Gift list public

### ISSUE THREAD

**Issue by davide-casiraghi** [davide-casiraghi/ci-global-calendar#25]
Create a page to show the gift lift to everybody.
The page should get data from the gift from list table trough the form in the Get Involved page.

**Comment by davide-casiraghi** [comment]
I've started to prepare the page. The first version is almost done.
**We need somebody that do the leg job to data entry all the contents from the excel gift list to the donation offer interface**.

**Comment by stawastawa** [comment]
> I've started to prepare the page. The first version is almost done.
> **We need somebody that do the leg job to data entry all the contents from the excel gift list to the donation offer interface**.

I could do this! how do I access the donation offer interface?

**Comment by davide-casiraghi** [comment]
We need to add some more details to the donations before adding the all the data. I let you know when we have done. It will not be in the next 10 days.
Thank you for you offer!

**Comment by davide-casiraghi** [comment]
The donation page is done. I guess now the team will self care to migrate the donations from the excel.
Stawastawa if we need any help I will contact you.
