### ISSUE TITLE
My Profile Email address cannot be updated unless Admin

### ISSUE THREAD

**Issue by wwwerk** [davide-casiraghi/ci-global-calendar#62]
**Describe the bug**
When attempting to change the email address for the logged-in (current) profile, and error is thrown: "You do not have admin access"

**To Reproduce**
1. Go to My Profile > Email Address > Submit

**Expected behavior**
All users should be able to update their profile email address.

**Screenshots**
![Screen Shot 2019-03-28 at 12 39 55 PM](https://user-images.githubusercontent.com/10946317/55189228-929a4100-515a-11e9-8948-d9650e23516d.png)

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by davide-casiraghi** [comment]
Fixed. 
Please text again and if works close the ticket.

**Comment by davide-casiraghi** [comment]
Going trough this issue again, I've noticed that was still needing some improvements.
Please check again.

Now the user is able to change email and password.
