### ISSUE TITLE
Associate Teachers with Event not maintained by Event creator

### ISSUE THREAD

**Issue by wwwerk** [davide-casiraghi/ci-global-calendar#64]
**Is your feature request related to a problem? Please describe.**
Many classes and jams are co-facilitated by a rotation of teachers. 

**Describe the solution you'd like**
The profile creating an event should be able to associate Teachers created by other accounts with classes.  Otherwise, a single account must maintain Teacher information for other teachers and facilitators who might otherwise prefer to maintain this information themselves, with their own account.

**Describe alternatives you've considered**
Workaround: a single user must create Teacher entries for other persons, and centrally manage them from a single account.

**Comment by davide-casiraghi** [comment]
> The profile creating an event should be able to associate Teachers created by other accounts with classes.

This is already possible. 
You don't see the other teachers when you are in the event creation page?

**Comment by davide-casiraghi** [comment]
closed due to inactivity
