### ISSUE TITLE
Teacher Directory: Next Page resets Country filter

### ISSUE THREAD

**Issue by wwwerk** [davide-casiraghi/ci-global-calendar#65]
**Describe the bug**
When applying a country filter, the filter is reset following click through to next page.

Token and keywords are not passed by url GET

BEFORE:
https://ciglobalcalendar.net/teachersDirectory?_token=bH997ENSVhbMCGUa4SLOpedWXgKQN0trDq1Fl8XP&keywords=&country_id=2

AFTER:
https://ciglobalcalendar.net/teachersDirectory?page=2

**To Reproduce**
1. Teacher Directory > Filter by Country 
2. Click Pagination: 2 (or next page)

**Expected behavior**
Filter should be maintained with pagination, token and country_id passed by URL GET

**Comment by davide-casiraghi** [comment]
Fixed. 
Please text again and if works close the ticket.
