### ISSUE TITLE
Teacher Management: New Teacher creation may not save uploaded image 

### ISSUE THREAD

**Issue by wwwerk** [davide-casiraghi/ci-global-calendar#68]
**Describe the bug**
When creating a New Teacher entry, a profile image was specified and uploaded. 
Subsequently, the image did not appear in My Teachers, or in Teacher Directory

**Workaround**
Returning to Edit Teacher and add image again produces the expected results, and image appears.

**Note** 
I have not tried to reproduce this issue by creating a New Teacher, but I may try.

**Comment by davide-casiraghi** [comment]
There was a bug related to this, I fix it last week. 
When you did create your account? Can you try again both the creation and the edit and tell me if is still present in just one of both of situations?

**Comment by davide-casiraghi** [comment]
This fix has HI priority since many teachers are still without profile image 
and we want to send a message to all the users asking to upload them before the roll-out.

**Comment by davide-casiraghi** [comment]
I've tested again now to:
- create a new teacher uploading the image (works)
- editing the teacher without changing the image (works - keep the image)
- editing the teacher changing the image (works - keep the new image)
- creating a teacher from the event creation, clicking on [create new teacher] button (works - keep the image)

**Comment by davide-casiraghi** [comment]
I've also added some constraints to the image upload.
Now the image has to be jpg, jpeg or png. And the max upload size is 3MB.
In case is bigger a website that provide an easy online resize service is provided.
