### ISSUE TITLE
Event creation: Adding a venue or teacher does not save previously entered content

### ISSUE THREAD

**Issue by CIGCAdmin** [davide-casiraghi/ci-global-calendar#72]
**Describe the bug**
When creating a New Event entry, the user has to specify a related venue and teacher.
This can be done through a pop up menu.
If the user has entered content previously, it disappears when opening the pop up and is lost.

**Expected behavior**
That the content is saved when the user returns to the Event Creation page.

**Workaround**
An alternative would be to re-organise the page and make it compulsory to enter the location and teacher first and before any other content can be filled in.

**Comment by davide-casiraghi** [comment]
We can redesign the venue, teacher and organizer sections creating three VueJS components..
So the page doesn’t need to reloaded.

Here is a good strategy to use some blade code in a VueJS component.
[https://stackoverflow.com/questions/45163567/how-can-i-use-blade-in-vue-files](https://stackoverflow.com/questions/45163567/how-can-i-use-blade-in-vue-files)

**Comment by davide-casiraghi** [comment]
I've developed it using AJAX in the modal pages.
Now the create event page when a teacher, venue or organizer is added doesn't need to reload any more.
