### ISSUE TITLE
Homepage Events Search - Provide State/Region filter

### ISSUE THREAD

**Issue by CIGCAdmin** [davide-casiraghi/ci-global-calendar#82]
**Is your feature request related to a problem? Please describe.**
In the case of a country with many events and/or long distances, it would be helpful to include the State/Region where the event is located. As an example, a US user pointed out that a full list of events for the whole country without the possibility to search per State, makes it difficult to discover new/unknown jams within driving distance

**Describe the solution you'd like**
Add State/Region field to events listing search results.

**Comment by davide-casiraghi** [comment]
- [x] Add in the davide-casiraghi/laravel-events-calendar package a regional model/controller/views and the relative table
- [x] Add the proper tests in the davide-casiraghi/laravel-events-calendar package
- [x] Add in the homepage the regional filter
- [x] Add the regions of the pilot countries with more events to the DB (Usa, Canada, Italy, Germany, France, Israel, Australia, UK)
- [x] Add the new required translation strings to the package
- [x] Fix the package tests that shows error
- [x] Fix the calendar tests that shows error
- [ ] Test the package in the test environment
- [ ] Roll out in production environment

**Comment by davide-casiraghi** [comment]
What are the meaningful subdivision of:
- Spain
- Switzerland
- Austria
- India
- China

**Comment by davide-casiraghi** [comment]
Rolled out on 25 December 2019
